In [4]:
#Tamim Mahmud from Daffodil International University
#08/07/2025
#Day 17
import torch 
print("PyTorch version:",torch.__version__)

PyTorch version: 2.7.1+cpu


part->01

Tensor Basick


torch.tensor([1,2,3,4])

In [6]:
x=torch.rand(3,3)
print(x)

tensor([[0.7691, 0.3656, 0.2309],
        [0.2860, 0.1842, 0.7448],
        [0.9811, 0.8228, 0.4391]])


In [7]:
y=torch.rand(4,4)
print(y)

tensor([[8.3935e-01, 9.9616e-01, 7.3642e-01, 5.3453e-01],
        [2.9939e-01, 9.6072e-01, 2.3880e-01, 4.0233e-01],
        [6.1577e-01, 8.5763e-01, 7.2397e-01, 6.2352e-04],
        [3.1278e-01, 4.9627e-02, 1.0049e-01, 2.1151e-01]])


In [8]:
import torch
print(torch.cuda.is_available())

False


In [9]:
x=torch.empty(1)
x

tensor([0.0002])

In [10]:
x=torch.empty(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
x=torch.empty(2,3,4)
x

tensor([[[1.8597e-04, 1.7278e-42, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [12]:
x.size

<function Tensor.size>

In [13]:
x.ndim

3

In [14]:
x=torch.zeros(3,3,3)
x

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [15]:
x=torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
d=torch.full((2,3,3),fill_value=8)
d

tensor([[[8, 8, 8],
         [8, 8, 8],
         [8, 8, 8]],

        [[8, 8, 8],
         [8, 8, 8],
         [8, 8, 8]]])

In [17]:
s=torch.full((3,3),fill_value=100)
s

tensor([[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]])

In [18]:
x=torch.empty(2,3,2,dtype=torch.double)
x

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]], dtype=torch.float64)

In [19]:
x=torch.tensor([1,2,3,4])
x

tensor([1, 2, 3, 4])

In [28]:
x=torch.rand(2,2)
y=torch.rand(2,2)
y.mul_(x)
print(y)

tensor([[0.5221, 0.3800],
        [0.0026, 0.1635]])


In [29]:
d=torch.mul(x,y)
d

tensor([[4.6320e-01, 1.9072e-01],
        [1.0135e-04, 1.1251e-01]])

In [32]:
x=torch.ones(5,requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [40]:
x=torch.ones(5,requires_grad=True)
y=x*2
z=y.sum()
z.backward()
print(x.grad)
print(z)

tensor([2., 2., 2., 2., 2.])
tensor(10., grad_fn=<SumBackward0>)


In [38]:
x=torch.tensor([2.0],requires_grad=True)
y=x**3+x**2+3*x
y.backward()
print("x=  ",x.item())
print("y=  ",y.item())
print("Gradient dy/dx : ",x.grad.item())

x=   2.0
y=   18.0
Gradient dy/dx :  19.0


In [55]:
x=torch.randn(3,requires_grad=True)
y=x**5+x**4+x**3+x**2+5*x
y=y.sum()
y.backward()
print(y)
print(x.grad)

tensor(-9.9597, grad_fn=<SumBackward0>)
tensor([ 5.3618,  5.2379, 11.0115])


In [62]:
#3 ways for stop gradient function
x=torch.randn(3,requires_grad=True)
print(x)
print()
x=requires_grad=False
print(x)

with torch.no_grad():
    z=x
    print(z)

tensor([ 0.4939,  0.6736, -1.1457], requires_grad=True)

False
False


In [64]:
w=torch.ones(4,requires_grad=True)
for epoch in range(4):
    output=(w*3).sum()
    output.backward()
    print(w.grad)
    w.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [65]:
import torch

w=torch.ones(4,requires_grad=True)
optimizer=torch.optim.SGD([w],lr=0.01)

output=(w*3).sum()

output.backward()

optimizer.step()

optimizer.zero_grad()

print(w)

tensor([0.9700, 0.9700, 0.9700, 0.9700], requires_grad=True)


In [66]:
#Part 1 is completed 

Part->2

Autograd & Gradient Descent

In [72]:
x=torch.tensor(4.0,requires_grad=True)
y=x**3+x**2+5*x
y.backward()
print(x)
print(y)
print(x.grad)

tensor(4., requires_grad=True)
tensor(100., grad_fn=<AddBackward0>)
tensor(61.)


In [74]:
x=torch.tensor(4.0,requires_grad=False)
print(x.grad)

None


In [ ]:
import torch
import matplotlib.pyplot as plt
w=0.0
lr=0.01
epoch=25
loss_list=[]
w_list=[]

for i in range(epoch):
    loss=(2*w-4)**2
    grad=8*w-16
    w=w-lr*grad
    loss_list.append(loss)
    w_list.append(w)
    print(f"Epoch{i+1}:  w=  {w:.4f}, loss={loss:.4f}")

plt.plot(loss_list)
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Manually Gradient Descent Loss")
plt.show()


    
    
  
    
   




In [37]:
c

[CE] Epoch 1, Loss: 0.6644
[CE] Epoch 101, Loss: 0.2301
[CE] Epoch 201, Loss: 0.1618
[CE] Epoch 301, Loss: 0.1330
[CE] Epoch 401, Loss: 0.1100
[CE] Epoch 501, Loss: 0.0930
[CE] Epoch 601, Loss: 0.0808
[CE] Epoch 701, Loss: 0.0720
[CE] Epoch 801, Loss: 0.0660
[CE] Epoch 901, Loss: 0.0611
[CE] Accuracy: 70.27%
